services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public:/var/www/html/public
    depends_on:
      - php
    networks:
      - default


networks:
  default:
    driver: bridge